### ISSUE TITLE
TSLint will soon be deprecated

### ISSUE THREAD

**Issue by bd82** [SAP/vscode-mta-tools#3]
It seems ESLint will now support TypeScript linting as well.
- https://github.com/typescript-eslint/typescript-eslint

There also seems to be multiple TSLint configurations.
- https://github.com/SAP/vscode-mta-tools/blob/master/tslint.json
- https://github.com/SAP/vscode-mta-tools/blob/master/tslint.yml

**Comment by rayakoren** [comment]
Issue is fixed in: [](https://github.com/SAP/vscode-mta-tools/pull/82)
